#Gradle
org.gradle.jvmargs=-Xmx2048M -Dfile.encoding=UTF-8 -Dkotlin.daemon.jvm.options\="-Xmx2048M"
#Kotlin
kotlin.code.style=official
#Android
android.useAndroidX=true
android.nonTransitiveRClass=true
#MPP
kotlin.mpp.enableCInteropCommonization=true
kotlin.mpp.androidSourceSetLayoutVersion=2
ksp.incremental=false

# ====== Maven ???? ======
# ??????publish-maven.sh ???
MAVEN_VERSION=1.0.0
# Maven Group ID
GROUP_ID=com.tencent.kuiklybase
# Kotlin ????????????????
KOTLIN_VERSION_LIST=2.0.21
# ????? Kotlin ??????????????????????????
OHOS_KOTLIN_VERSION_LIST=2.0.21-KBA-010
# Maven ????
MAVEN_REPO_URL=xxx
MAVEN_USERNAME=xxx
MAVEN_PASSWORD=xxx